"""Initial schema

Revision ID: 2be6c878e8a5
Revises: 
Create Date: 2026-02-15 15:20:58.464663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2be6c878e8a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique provider identifier'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Provider name (e.g., 'stripe', 'github')"),
    sa.Column('secret_key', sa.String(length=500), nullable=False, comment='HMAC secret key for signature verification'),
    sa.Column('forwarding_url', sa.String(length=500), nullable=False, comment='Internal service URL to forward validated webhooks'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this provider is currently active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this provider was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When this provider was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique log entry identifier'),
    sa.Column('provider_name', sa.String(length=100), nullable=False, comment='Provider name from request'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type of security event'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Source IP address'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Request ID if available'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional event details (JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this event occurred'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_created_at'), 'security_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_logs_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_logs_ip_address'), 'security_logs', ['ip_address'], unique=False)
    op.create_index('ix_security_logs_ip_created', 'security_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_security_logs_provider_name'), 'security_logs', ['provider_name'], unique=False)
    op.create_index('ix_security_logs_provider_type_created', 'security_logs', ['provider_name', 'event_type', 'created_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique event identifier'),
    sa.Column('provider_id', sa.UUID(), nullable=False, comment='Which provider sent this webhook'),
    sa.Column('request_id', sa.String(length=255), nullable=False, comment='Unique request ID for idempotency'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Webhook payload (JSON)'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Request headers (JSON)'),
    sa.Column('signature_valid', sa.Boolean(), nullable=False, comment='Whether HMAC signature was valid'),
    sa.Column('forwarded', sa.Boolean(), nullable=False, comment='Whether webhook was forwarded to internal service'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP status code from forwarding attempt'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='HTTP response body from forwarding attempt'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('received_at', sa.DateTime(), nullable=False, comment='When webhook was received'),
    sa.Column('forwarded_at', sa.DateTime(), nullable=True, comment='When webhook was forwarded'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_provider_received', 'webhook_events', ['provider_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_request_id'), 'webhook_events', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_request_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_received', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_security_logs_provider_type_created', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_provider_name'), table_name='security_logs')
    op.drop_index('ix_security_logs_ip_created', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_ip_address'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_event_type'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_created_at'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
